---
title: "Untitled"
author: "Nuno Fernandes"
date: '2023-02-25'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r}
df = read.csv("datable_R.csv")

```


```{r}
str(df)
```

```{r}
library(lme4)
library(afex) #for p-values
m1=lmer(mean_predictions~congruent + sym+ gender + congruent*sym*gender + (1|parse), data = df)
summary(m1)
car::Anova(m1)
```
```{r}
anova(m1)
```

```{r}
library("report")
report(m1)
```

```{r}
library(sjPlot)
tab_model(m1)
```

```{r}
library(emmeans)
noise <- emmeans(m1,~congruent*sym*gender)


x = contrast(noise, "pairwise", simple = "each", combine = TRUE, adjust="bonf")
x
```
```{r}
confint(x)
```

```{r}
eff_size(noise, sigma=sigma(m1), edf = df.residual(m1))
```

```{r}
df
```


#### Apa theme
```{r}
#apa
theme_apa <- function(base_size = 12, base_family = "", box = FALSE) {
  adapted_theme <- ggplot2::theme_bw(base_size, base_family) +
    ggplot2::theme(
      plot.title = ggplot2::element_text(size = ggplot2::rel(1.1), margin = ggplot2::margin(0, 0, ggplot2::rel(14), 0), hjust = 0.5)
      , plot.subtitle = ggplot2::element_text(size = ggplot2::rel(0.8), margin = ggplot2::margin(ggplot2::rel(-7), 0, ggplot2::rel(14), 0), hjust = 0.5)

      # , axis.title = ggplot2::element_text(size = ggplot2::rel(1.1))
      , axis.title.x = ggplot2::element_text(size = ggplot2::rel(1), lineheight = ggplot2::rel(1.1), margin = ggplot2::margin(ggplot2::rel(12), 0, 0, 0))
      , axis.title.x.top = ggplot2::element_text(size = ggplot2::rel(1), lineheight = ggplot2::rel(1.1), margin = ggplot2::margin(0, 0, ggplot2::rel(12), 0))
      , axis.title.y = ggplot2::element_text(size = ggplot2::rel(1), lineheight = ggplot2::rel(1.1), margin = ggplot2::margin(0, ggplot2::rel(12), 0, 0))
      , axis.title.y.right = ggplot2::element_text(size = ggplot2::rel(1), lineheight = ggplot2::rel(1.1), margin = ggplot2::margin(0, 0, 0, ggplot2::rel(12)))
      , axis.ticks.length = ggplot2::unit(ggplot2::rel(6), "points")
      , axis.text = ggplot2::element_text(size = ggplot2::rel(0.9))
      , axis.text.x = ggplot2::element_text(size = ggplot2::rel(1), margin = ggplot2::margin(ggplot2::rel(6), 0, 0, 0))
      , axis.text.y = ggplot2::element_text(size = ggplot2::rel(1), margin = ggplot2::margin(0, ggplot2::rel(6), 0, 0))
      , axis.text.y.right = ggplot2::element_text(size = ggplot2::rel(1), margin = ggplot2::margin(0, 0, 0, ggplot2::rel(6)))
      , axis.line = ggplot2::element_line()
      # , axis.line.x = ggplot2::element_line()
      # , axis.line.y = ggplot2::element_line()

      , legend.title = ggplot2::element_text()
      , legend.key = ggplot2::element_rect(fill = NA, color = NA)
      , legend.key.width = ggplot2::unit(ggplot2::rel(20), "points")
      , legend.key.height = ggplot2::unit(ggplot2::rel(20), "points")
      , legend.margin = ggplot2::margin(
        t = ggplot2::rel(16)
        , r = ggplot2::rel(16)
        , b = ggplot2::rel(16)
        , l = ggplot2::rel(16)
        , unit = "points"
      )

      , panel.spacing = ggplot2::unit(ggplot2::rel(14), "points")
      , panel.grid.major.x = ggplot2::element_blank()
      , panel.grid.minor.x = ggplot2::element_blank()
      , panel.grid.major.y = ggplot2::element_blank()
      , panel.grid.minor.y = ggplot2::element_blank()

      , strip.background = ggplot2::element_rect(fill = NA, color = NA)
      , strip.text.x = ggplot2::element_text(size = ggplot2::rel(1.2), margin = ggplot2::margin(0, 0, ggplot2::rel(10), 0))
      , strip.text.y = ggplot2::element_text(size = ggplot2::rel(1.2), margin = ggplot2::margin(0, 0, 0, ggplot2::rel(10)))
    )

  if(box) {
    adapted_theme <- adapted_theme + ggplot2::theme(panel.border = ggplot2::element_rect(color = "black"))
  } else {
    adapted_theme <- adapted_theme + ggplot2::theme(panel.border = ggplot2::element_blank())
  }

  adapted_theme
}

```

```{r}
library(dplyr)
df %>% group_by(gender,sym, congruent) %>% summarize(ratings = mean(mean_predictions), se = sd(mean_predictions)/sqrt(length(mean_predictions))) -> df_plot

df_plot = data.frame(df_plot)
colnames(df_plot) = c( "Gender"   , "sym"      , "Congruent", "ratings" ,  "se" )
```

```{r} 
library(ggplot2)
grid_names <- c(
                    "no" = "Non-Symmetrized",
                    "yes" = "Symmetrized"
                    )
df_plot$Gender[df_plot$Gender=="female"] <-"Female"
df_plot$Gender[df_plot$Gender=="male"] <-"Male"

df_plot$Congruent[df_plot$Congruent=="masculinized"] <-"Masculinized"
df_plot$Congruent[df_plot$Congruent=="feminized"] <-"Feminized"
df_plot$Congruent[df_plot$Congruent=="original"] <-"Original"

ggplot(df_plot, aes(x = factor(Gender), y = ratings, group = Congruent)) + geom_point(size = 3, aes(colour = Congruent,  shape = Congruent), position=position_dodge(width=c(0.7))) +geom_line(size = 0.5, aes(linetype=Congruent, color = Congruent),position=position_dodge(width=c(0.7))) + facet_wrap(~sym, labeller = as_labeller(grid_names)) + theme_apa() +ylab("Predicted Attractiveness")  + xlab("Condition")+ geom_errorbar(aes(ymin=(ratings-se), ymax=ratings+se, color = Congruent), width=.2, position=position_dodge(0.7)) +   scale_color_manual(values = c("black","#8c8c8c","#cccccc")) +guides(col = guide_legend(override.aes = list(shape = c(16, 17,15), color = c("black", "#8c8c8c","#cccccc")))) + coord_cartesian(expand = FALSE, ylim = c(0.45,0.555))
```